In [1]:
import pandas as pd
import requests as req
from bs4 import BeautifulSoup as bs

In [2]:
url = "https://libgen.li/index.php?req=machine+learning&columns%5B%5D=t&objects%5B%5D=f&topics%5B%5D=l&res=100&covers=on&filesuns=all"

response = req.get(url)
soup = bs(response.content,"html")
print(soup.prettify())

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="max-age=604800, must-revalidate" http-equiv="CACHE-CONTROL"/>
  <meta content="general" name="rating"/>
  <!--<link href="/rss/index.php" rel="alternate" type="application/rss+xml" title="News" />-->
  <link href="/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <title>
   Library Genesis
  </title>
  <!--[if IE 6]>
	<style>
		body {behavior: url("/csshover3.htc");}
		#menu li .drop {background:url("img/drop.gif") no-repeat right 8px;
	</style>
	<![endif]-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="/css/font.min.css" rel="stylesheet"/>
  <style>
   nav.navbar .dropdown:hover > .dropdown-menu {
 display: block;
}
.bd-placeholder-img {
	font-size: 1.125rem;
	text-anchor: middle;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}
@media (min-width: 768px) {
			.bd-placeholder-img-lg {
			font-size: 3.5rem;
		}
	}

.panel-heading .accordion-toggle:after {
    font-family: "Glyphicons Halflings";
    content: "\e114";
    float: right;
    color: grey;
}
.panel-heading .accordion-toggle.collapsed:after {
    content: "\e080";
}
.tooltip-inner {
    max-width: 350px;
    width: 350px;
}
h1 {
	display: block;
	font-size: 1.8rem;
	font-weight: bold;
	font-family: Georgia, "Times New Roman", Times, serif;  color: #A00000;
}
#tablelibgen td {
	font-family: "Pt Sans", Tahoma, Helvetica, sans-serif;
	margin: 0;
	padding: 0em 3px;
	font-size: 1rem;
}

#tablelibgen1 td {
	font-family: "Pt Sans", Tahoma, Helvetica, sans-serif;
	margin: 0;
	padding: 0em 3px;
	font-size: 1rem;
}

.taghide {
    display: none;
}
.taghide + label ~ div {
    display: none;
}
/* оформляем текст label */
.taghide + label {
    display: inline-block;
}
/* вид текста label при активном переключателе */

/* когда чекбокс активен показываем блоки с содержанием  */
.taghide:checked + label + div {
    display: block;
}



/*.navbar {
	background-color: #BBBBBB;
}*/
  </style>
  <link href="/css/dark-mode.css" rel="stylesheet"/>
  <script crossorigin="anonymous" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" src="https://code.jquery.com/jquery-3.6.0.min.js">
  </script>
  <link href="../css/paginator3000.css" rel="stylesheet" type="text/css"/>
  <script src="../js/paginator3000.js" type="text/javascript">
  </script>
  <script src="//inopportunefable.com/28/4b/51/284b513767b1a27086dec8171527696f.js" type="text/javascript">
  </script>
 </head>
 <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-secondary mb-1">
   <a class="navbar-brand" href="/index.php">
    <img alt="" height="30" src="/img/logo.png"/>
   </a>
   <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarCollapse" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon">
    </span>
   </button>
   <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
     <li class="nav-item active">
      <a class="nav-link" href="/community/app.php/article/news">
       NEWS
       <span class="sr-only">
        (current)
       </span>
      </a>
     </li>
     <li class="nav-item active">
      <a class="nav-link" href="/community/">
       FORUM
       <span class="sr-only">
        (current)
       </span>
      </a>
     </li>
     <li class="nav-item dropdown">
      <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary dropdown-toggle" href="/community/ucp.php?mode=login" id="dropdownMenuLink" role="button">
       LOGIN
      </a>
      <div aria-labelledby="dropdown01" class="dropdown-menu">
       <a class="dropdown-item" href="/community/ucp.php?mode=register">
        Register
       </a>
      </div>
     </li>
     <li class="nav-item dropdown">
      <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary dropdown-toggle" href="#" id="dropdownMenuLink" role="button">
       DOWNLOAD
      </a>
      <div aria-labelledby="dropdown01" class="dropdown-menu">
       <a class="dropdown-item" href="/mirrors.php">
        Mirrors
       </a>
       <a class="dropdown-item" href="http://libgenfrialc7tguyjywa36vtrdcplwpxaw43h6o63dmmwhvavo5rqqd.onion/">
        TOR
       </a>
       <div class="dropdown-divider">
       </div>
       <h6 class="dropdown-header">
        P2P
       </h6>
       <a class="dropdown-item" href="/torrents/">
        Torrents
       </a>
       <a class="dropdown-item" href="https://ipdl.cat/data/torrents.html">
        Torrents status
       </a>
       <a class="dropdown-item" href="/nzb/">
        Usenet (*.nzb)
       </a>
       <a class="dropdown-item" href="/soft/">
        Soft
       </a>
       <!--https://phillm.net/libgen-stats-table.php-->
       <div class="dropdown-divider">
       </div>
       <h6 class="dropdown-header">
        DB Dumps
       </h6>
       <a class="dropdown-item" href="/dirlist.php?dir=dbdumps">
        Libgen
       </a>
       <a class="dropdown-item" href="http://libgen.rs/dbdumps/">
        libgen.rs (gen.lib.rus.ec)
       </a>
       <!--<div class="dropdown-divider"></div>
 	 <a class="dropdown-item" href="/magz0/">Unsorted magz</a>
 	 <a class="dropdown-item" href="/fict0/">Unsorted fiction</a>

	 <a class="dropdown-item" href="/comics4/">Unsorted comics</a>
        </div>-->
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary dropdown-toggle" href="librarian.php" id="dropdownMenuLink" role="button">
         UPLOAD
        </a>
        <div aria-labelledby="dropdown01" class="dropdown-menu">
         <a class="dropdown-item" href="ftp://ftp.libgen.bz/upload/">
          FTP
         </a>
        </div>
       </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary dropdown-toggle" href="/index.php?req=fmode:last&amp;topics1=all" id="dropdownMenuLink" role="button">
         LAST
        </a>
        <div aria-labelledby="dropdown01" class="dropdown-menu">
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics1=all">
          <b>
           Files
          </b>
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=l">
          Libgen
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=a">
          Scientific Articles
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=f">
          Fiction
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=c">
          Comics
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=m">
          Magazines
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=s">
          Standards
         </a>
         <a class="dropdown-item" href="/index.php?req=fmode:last&amp;topics%5B%5D=r">
          Fiction RUS
         </a>
         <div class="dropdown-divider">
         </div>
         <a class="dropdown-item" href="/index.php?req=mode:last&amp;curtab=e">
          Editions
         </a>
         <a class="dropdown-item" href="/index.php?req=mode:last&amp;curtab=s">
          Series
         </a>
         <a class="dropdown-item" href="/index.php?req=mode:last&amp;curtab=p">
          Publishers
         </a>
         <!--  <a class="dropdown-item" href="/index.php?req=mode:last&curtab=f">Files</a> -->
         <a class="dropdown-item" href="/index.php?req=mode:last&amp;curtab=a">
          Authors
         </a>
         <a class="dropdown-item" href="/index.php?req=mode:last&amp;curtab=w">
          Works
         </a>
        </div>
       </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary dropdown-toggle" href="#" id="dropdownMenuLink" role="button">
         OTHERS
        </a>
        <div aria-labelledby="dropdown01" class="dropdown-menu">
         <a class="dropdown-item" href="json.php">
          API
         </a>
         <a class="dropdown-item" href="rss.php">
          RSS
         </a>
         <a class="dropdown-item" href="top.php">
          Top 100 users
         </a>
         <a class="dropdown-item" href="stat.php">
          Stats
         </a>
         <a class="dropdown-item" href="topics.php">
          Topics
         </a>
         <a class="dropdown-item" href="batchsearchindex.php">
          Batch search
         </a>
         <a class="dropdown-item" href="biblioservice.php">
          Bibliographic services
         </a>
         <a class="dropdown-item" href="https://wiki.mhut.org/software:libgen_desktop">
          Libgen librarian for desktop
         </a>
         <a class="dropdown-item" href="/code/">
          Source (PHP)
         </a>
         <a class="dropdown-item" href="/soft/">
          LG soft
         </a>
         <!--<a class="dropdown-item" href="/import/">Import local files in LG format</a>-->
         <a class="dropdown-item" href="https://z-library.se/fulltext/">
          Full text search
         </a>
        </div>
       </li>
       <!-- <li class="nav-item dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="topics.php" role="button" id="dropdownMenuLink"  aria-haspopup="true" aria-expanded="false">
          Topics
        </a>
      </li>
-->
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary dropdown-toggle" href="#" id="dropdownMenuLink" role="button">
         LINKS
        </a>
        <div aria-labelledby="dropdown01" class="dropdown-menu">
         <a class="dropdown-item" href="http://sci-hub.ru">
          Sci-hub
         </a>
         <a class="dropdown-item" href="http://magzdb.org">
          Magzdb.org
         </a>
         <a class="dropdown-item" href="http://nlr.ru/rlin/Periodika_rus.php">
          РНБ
         </a>
         <a class="dropdown-item" href="http://rsl.ru/">
          РГБ
         </a>
         <a class="dropdown-item" href="http://loc.gov/">
          LOC
         </a>
         <a class="dropdown-item" href="https://comicvine.gamespot.com/">
          ComicVine
         </a>
         <a class="dropdown-item" href="http://cyberleninka.ru/">
          Cyberleninka
         </a>
         <a class="dropdown-item" href="http://lib.rus.ec/">
          Lib.rus.ec
         </a>
         <a class="dropdown-item" href="http://flibusta.net/">
          Flibusta.net
         </a>
         <a class="dropdown-item" href="http://goodreads.com/">
          Goodreads.com
         </a>
         <a class="dropdown-item" href="http://worldcat.org/">
          Worldcat.org
         </a>
         <a class="dropdown-item" href="https://wiki.archiveteam.org/">
          Archive team
         </a>
         <a class="dropdown-item" href="https://www.reddit.com/r/libgen/">
          Reddit
         </a>
         <a class="dropdown-item" href="http://annas-archive.org/">
          Anna's Archive
         </a>
         <a class="dropdown-item" href="https://welib.org/">
          Welib
         </a>
         <a class="dropdown-item" href="https://open-slum.org/">
          The Shadow Library Uptime Monitor
         </a>
        </div>
       </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="btn btn-secondary" href="index.php?req=mode:req&amp;curtab=e" id="dropdownMenuLink" role="button">
         WANTED
        </a>
       </li>
      </div>
      <div class="nav-link">
       <div class="custom-control custom-switch">
        <input class="custom-control-input" id="darkSwitch" type="checkbox"/>
        <label class="custom-control-label" for="darkSwitch">
         🌓
        </label>
       </div>
       <script src="/js/dark-mode-switch.js">
       </script>
      </div>
      <a class="navbar-brand" href="setlang.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;lang=ru">
       RU
      </a>
      <form action="index.php" class="card p-2 needs-validation" enctype="multipart/form-data" id="formlibgen" method="GET" novalidate="">
       <div class="input-group mb-3">
        <input aria-describedby="button-addon2" aria-label="input text" autofocus="" class="form-control" name="req" placeholder="Input value" required="" type="text" value="machine learning"/>
        <div class="input-group-append">
         <button class="btn btn-outline-secondary" id="button-addon2" type="submit">
          🔍
         </button>
        </div>
        <div class="invalid-feedback">
         Input value
        </div>
       </div>
       <div class="container-fluid">
        <div class="row">
         <div class="col-8">
          <div class="d-block" id="topic">
           <strong>
            Search in fields:
           </strong>
           <input checked="" class="column-input" id="colt" name="columns[]" type="checkbox" value="t"/>
           <label class="column-label" for="coltitle">
            Title
           </label>
           <input class="column-input" id="cola" name="columns[]" type="checkbox" value="a"/>
           <label class="column-label" for="colauthor">
            Author(s)
           </label>
           <input class="column-input" id="cols" name="columns[]" type="checkbox" value="s"/>
           <label class="column-label" for="colseries">
            Series
           </label>
           <input class="column-input" id="coly" name="columns[]" type="checkbox" value="y"/>
           <label class="column-label" for="colyear">
            Year
           </label>
           <input class="column-input" id="colp" name="columns[]" type="checkbox" value="p"/>
           <label class="column-label" for="colpublisher">
            Publisher
           </label>
           <input class="column-input" id="coli" name="columns[]" type="checkbox" value="i"/>
           <label class="column-label" for="colisbn">
            ISBN
           </label>
          </div>
          <div class="d-block" id="object">
           <strong>
            Search in objects:
           </strong>
           <input checked="" class="column-input" id="objf" name="objects[]" type="checkbox" value="f"/>
           <label class="column-label" for="objf">
            Files
           </label>
           <input class="column-input" id="obje" name="objects[]" type="checkbox" value="e"/>
           <label class="column-label" for="obje">
            Editions
           </label>
           <input class="column-input" id="objs" name="objects[]" type="checkbox" value="s"/>
           <label class="column-label" for="objs">
            Series
           </label>
           <input class="column-input" id="obja" name="objects[]" type="checkbox" value="a"/>
           <label class="column-label" for="obja">
            Authors
           </label>
           <input class="column-input" id="objp" name="objects[]" type="checkbox" value="p"/>
           <label class="column-label" for="objp">
            Publishers
           </label>
           <input class="column-input" id="objw" name="objects[]" type="checkbox" value="w"/>
           <label class="column-label" for="objw">
            Works
           </label>
          </div>
          <div class="d-block" id="column">
           <strong>
            Search in topics :
           </strong>
           <input checked="" class="column-input" id="topl" name="topics[]" type="checkbox" value="l"/>
           <label class="column-label" for="topl">
            Libgen
           </label>
           <input class="column-input" id="topc" name="topics[]" type="checkbox" value="c"/>
           <label class="column-label" for="topc">
            Comics
           </label>
           <input class="column-input" id="topf" name="topics[]" type="checkbox" value="f"/>
           <label class="column-label" for="topf">
            Fiction
           </label>
           <input class="column-input" id="topa" name="topics[]" type="checkbox" value="a"/>
           <label class="column-label" for="topa">
            Scientific Articles
           </label>
           <input class="column-input" id="topm" name="topics[]" type="checkbox" value="m"/>
           <label class="column-label" for="topm">
            Magazines
           </label>
           <input class="column-input" id="topr" name="topics[]" type="checkbox" value="r"/>
           <label class="column-label" for="topr">
            Fiction RUS
           </label>
           <input class="column-input" id="tops" name="topics[]" type="checkbox" value="s"/>
           <label class="column-label" for="tops">
            Standards
           </label>
          </div>
         </div>
         <div class="col-4">
          <div>
           <strong>
            Results per page:
           </strong>
           <div class="custom-control custom-radio custom-control-inline">
            <input class="custom-control-input" id="res25" name="res" type="radio" value="25"/>
            <label class="custom-control-label" for="res25">
             25
            </label>
           </div>
           <div class="custom-control custom-radio custom-control-inline">
            <input class="custom-control-input" id="res50" name="res" type="radio" value="50"/>
            <label class="custom-control-label" for="res50">
             50
            </label>
           </div>
           <div class="custom-control custom-radio custom-control-inline">
            <input checked="" class="custom-control-input" id="res100" name="res" type="radio" value="100"/>
            <label class="custom-control-label" for="res100">
             100
            </label>
           </div>
          </div>
          <div class="d-block">
           <table>
            <tr>
             <td>
              <div class="custom-control custom-switch">
               <input checked="" class="custom-control-input" id="covers" name="covers" type="checkbox"/>
               <label class="custom-control-label" for="covers">
                <strong>
                 Show Covers
                </strong>
               </label>
               <script type="text/javascript">
                $("input[id=covers]").change(function(){
							if($(this).is(":checked")==false)
							{
								document.cookie = "covers=; expires=Thu 01-Jan-70 00:00:01 GMT;";
							}
						});
               </script>
              </div>
             </td>
             <td>
              <div class="custom-control custom-switch">
               <input class="custom-control-input" id="showch" name="showch" type="checkbox"/>
               <label class="custom-control-label" for="showch">
                <strong>
                 Show chapters
                </strong>
               </label>
               <script type="text/javascript">
                $("input[id=showch]").change(function(){
							if($(this).is(":checked")==false)
							{
								document.cookie = "showch=; expires=Thu 01-Jan-70 00:00:01 GMT;";
							}
						});
               </script>
              </div>
             </td>
            </tr>
           </table>
          </div>
          <div class="d-block">
           <div class="custom-control custom-switch">
            <input class="custom-control-input" id="gmode" name="gmode" type="checkbox"/>
            <label class="custom-control-label" for="gmode">
             <strong>
              Google mode

In [3]:
table = soup.find("table",{"class": "table"})
table

<table class="table table-striped" id="tablelibgen"><thead><tr>
<th scope="col"></th>
<th class="first_col" scope="col"><nobr>
ID <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=f_id&amp;ordermode=asc">↕</a>
Time add. <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=time_added&amp;ordermode=asc">↕</a>
Title <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=title&amp;ordermode=asc">↕</a>
Series <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=series&amp;ordermode=asc">↕</a></nobr></th>
<th scope="col"><nobr>Author(s) <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=author&amp;ordermode=asc">↕</a></nobr></th>
<th scope="col"><nobr>Publisher <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=publisher&amp;ordermode=asc">↕</a></nobr></th>
<th scope="col"><nobr>Year <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=year&amp;ordermode=asc">↕</a></nobr></th>
<th scope="col">Language</th>
<th scope="col">Pages</th>
<th scope="col"><nobr>Size  <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=filesize&amp;ordermode=asc">↕</a></nobr></th>
<th scope="col"><nobr>Ext. <a href="/index.php?req=machine+learning&amp;columns%5B%5D=t&amp;objects%5B%5D=f&amp;topics%5B%5D=l&amp;res=100&amp;covers=on&amp;filesuns=all&amp;curtab=f&amp;order=extension&amp;ordermode=asc">↕</a></nobr></th>
<th scope="col">Mirrors</th>
</tr></thead><tbody><tr>
<td><a href="edition.php?id=138581562"><img src="/covers/2804000/9ef62d66f3895c959fcd5efa13641ac2_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><b>Chapman &amp; Hall/CRC machine learning &amp; pattern recognition series<a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=138581562" title="Add/Edit : 2020-10-11/2021-09-12; ID: 93778618&lt;br&gt;Kroese D.P., et al. Data science and machine learning. Mathematical and statistical methods (CRC, 2020)(ISBN 9781138492530)(O)(536s)_MVsa_"><i></i></a></b><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=138581562" title="Add/Edit : 2020-10-11/2021-09-12; ID: 93778618&lt;br&gt;Kroese D.P., et al. Data science and machine learning. Mathematical and statistical methods (CRC, 2020)(ISBN 9781138492530)(O)(536s)_MVsa_">Data science and machine learning. Mathematical and statistical methods <i></i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=138581562" title="Add/Edit : 2020-10-11/2021-09-12; ID: 93778618&lt;br&gt;Kroese D.P., et al. Data science and machine learning. Mathematical and statistical methods (CRC, 2020)(ISBN 9781138492530)(O)(536s)_MVsa_"><i><font color="green"> 9781138492530; 1138492531</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 2804141</span></nobr>
</td>
<td>Botev, Zdravko I.; Kroese, Dirk P.; Taimre, Thomas; Vaisman, Radislav</td>
<td>Chapman &amp; Hall/CRC</td>
<td><nobr>2020</nobr></td>
<td>English</td>
<td>536 / xxi, 513 pages : illustrations, charts; 28 cm</td>
<td><nobr><a href="/file.php?id=93778618">15 MB</a></nobr></td>
<td>pdf</td>
<td><nobr><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=9ef62d66f3895c959fcd5efa13641ac2" title="libgen"><span class="badge badge-primary">1</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/9ef62d66f3895c959fcd5efa13641ac2" title="Randombook"><span class="badge badge-primary">2</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/9ef62d66f3895c959fcd5efa13641ac2?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">3</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/9ef62d66f3895c959fcd5efa13641ac2" title="libgen.pw"><span class="badge badge-primary">4</span></a> </nobr></td>
</tr><tr>
<td><a href="edition.php?id=205181687"><img src="/covers/6998000/bf97ee64d0bd2f0ded03cc0daa0cfe11_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=205181687" title="Add/Edit : 2026-01-11/2026-01-11; ID: 112533151&lt;br&gt;Masís, Serg - Interpretable Machine Learning with Python - Second Edition (Early Access) (2022, Packt Publishing)">Interpretable Machine Learning with Python - Second Edition (Early Access) <i>2nd</i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=205181687" title="Add/Edit : 2026-01-11/2026-01-11; ID: 112533151&lt;br&gt;Masís, Serg - Interpretable Machine Learning with Python - Second Edition (Early Access) (2022, Packt Publishing)"><i><font color="green"> 9781803235424; 180323542X; 9781118519639; 1118519639; 0000004820; 9780000004826; 0000046000; 9780000046000; 0406298920; 9780406298928; 0113289774; 9780113289776; 0467321930; 9780467321931</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 6998163</span></nobr>
</td>
<td>Masís, Serg</td>
<td>Packt Publishing</td>
<td><nobr>2022</nobr></td>
<td>English</td>
<td>0 / 357</td>
<td><nobr><a href="/file.php?id=112533151">11 MB</a></nobr></td>
<td>epub</td>
<td><nobr><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=bf97ee64d0bd2f0ded03cc0daa0cfe11" title="libgen"><span class="badge badge-primary">1</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/bf97ee64d0bd2f0ded03cc0daa0cfe11" title="Randombook"><span class="badge badge-primary">2</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/bf97ee64d0bd2f0ded03cc0daa0cfe11?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">3</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/bf97ee64d0bd2f0ded03cc0daa0cfe11" title="libgen.pw"><span class="badge badge-primary">4</span></a> </nobr></td>
</tr><tr>
<td><a href="edition.php?id=145761396"><img src="/covers/4793000/784ef93350602e47f7d6e9c35fe8f835_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=145761396" title="Add/Edit : 2023-07-13/2023-07-21; ID: 102010712&lt;br&gt;Ping, David - The Machine Learning Solutions Architect Handbook (Early Access) (2022, Packt Publishing)">The Machine Learning Solutions Architect Handbook (Early Access) <i></i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=145761396" title="Add/Edit : 2023-07-13/2023-07-21; ID: 102010712&lt;br&gt;Ping, David - The Machine Learning Solutions Architect Handbook (Early Access) (2022, Packt Publishing)"><i><font color="green"> 1801072167; 9781801072168; 2187000001; 9782187000004</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 4793251</span></nobr>
</td>
<td>Ping, David</td>
<td>Packt Publishing</td>
<td><nobr>2022</nobr></td>
<td>English</td>
<td>40 / 90</td>
<td><nobr><a href="/file.php?id=102010712">4 MB</a></nobr></td>
<td>epub</td>
<td><nobr><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=784ef93350602e47f7d6e9c35fe8f835" title="libgen"><span class="badge badge-primary">1</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/784ef93350602e47f7d6e9c35fe8f835" title="Randombook"><span class="badge badge-primary">2</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/784ef93350602e47f7d6e9c35fe8f835?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">3</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/784ef93350602e47f7d6e9c35fe8f835" title="libgen.pw"><span class="badge badge-primary">4</span></a> </nobr></td>
</tr><tr>
<td><a href="edition.php?id=153384576"><img src="" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=153384576" title="Add/Edit : 2025-08-04/2025-08-04; ID: 110350216&lt;br&gt;10.0000%2Fwww.cs.princeton.edu%2Fgeneric-32492339AFB0">Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification <i></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Report">rep</a></span>
<span class="badge badge-secondary">a 89622474</span></nobr>
</td>
<td>Schapire, Rob (author)</td>
<td></td>
<td><nobr></nobr></td>
<td></td>
<td>58</td>
<td><nobr><a href="/file.php?id=110350216">321 kB</a></nobr></td>
<td>pdf</td>
<td><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=ac44d14e8098614c1360576b5ab2fed0&amp;downloadname=10.0000/ac44d14e8098614c1360576b5ab2fed0" title="libgen"><span class="badge badge-primary">Libgen</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="http://sci-hub.ru/10.0000/ac44d14e8098614c1360576b5ab2fed0" title="sci-hub"><span class="badge badge-primary">Sci-Hub</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/ac44d14e8098614c1360576b5ab2fed0" title="Randombook"><span class="badge badge-primary">Randombook</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/ac44d14e8098614c1360576b5ab2fed0" title="libgen.pw"><span class="badge badge-primary">libgen.pw</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/ac44d14e8098614c1360576b5ab2fed0?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">Anna's arch</span></a> </td>
</tr><tr>
<td><a href="edition.php?id=205468968"><img src="/covers/7071000/9430cdecbdc42e2a59a52e5b96471b12_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=205468968" title="Add/Edit : 2026-01-12/2026-01-12; ID: 112820392&lt;br&gt;Shikha Agarwal &amp; Manish Gupta &amp; Jitendra Agrawal &amp; Dac-Nhuong Le &amp; Kamlesh Kumar Gupta - Swarm Intelligence and Machine Learning (2022, )">Swarm Intelligence and Machine Learning <i></i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=205468968" title="Add/Edit : 2026-01-12/2026-01-12; ID: 112820392&lt;br&gt;Shikha Agarwal &amp; Manish Gupta &amp; Jitendra Agrawal &amp; Dac-Nhuong Le &amp; Kamlesh Kumar Gupta - Swarm Intelligence and Machine Learning (2022, )"><i><font color="green"> 9781032145792; 103214579X; 9781032145822; 103214582X; 9781003240037; 1003240038; 9783030633073; 3030633071</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 7071918</span></nobr>
</td>
<td>Shikha Agarwal &amp; Manish Gupta &amp; Jitendra Agrawal &amp; Dac-Nhuong Le &amp; Kamlesh Kumar Gupta</td>
<td></td>
<td><nobr>2022</nobr></td>
<td>English</td>
<td>0</td>
<td><nobr><a href="/file.php?id=112820392">10 MB</a></nobr></td>
<td>fb2</td>
<td><nobr><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=9430cdecbdc42e2a59a52e5b96471b12" title="libgen"><span class="badge badge-primary">1</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/9430cdecbdc42e2a59a52e5b96471b12" title="Randombook"><span class="badge badge-primary">2</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/9430cdecbdc42e2a59a52e5b96471b12?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">3</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/9430cdecbdc42e2a59a52e5b96471b12" title="libgen.pw"><span class="badge badge-primary">4</span></a> </nobr></td>
</tr><tr>
<td><a href="edition.php?id=141871023"><img src="/covers/3511000/615b614a406e379ac2a01fd278414216_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><b>Adaptive Computation and Machine Learning<a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=141871023" title="Add/Edit : 2022-06-28/2022-07-10; ID: 97890631&lt;br&gt;Probabilistic Machine Learning An Introduction"><i></i></a></b><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=141871023" title="Add/Edit : 2022-06-28/2022-07-10; ID: 97890631&lt;br&gt;Probabilistic Machine Learning An Introduction">Probabilistic Machine Learning: An Introduction (Adaptive Computation and Machine Learning series) <i>1</i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=141871023" title="Add/Edit : 2022-06-28/2022-07-10; ID: 97890631&lt;br&gt;Probabilistic Machine Learning An Introduction"><i><font color="green"> 0262046822; 9780262046824</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 3511367</span></nobr>
</td>
<td>Kevin P. Murphy</td>
<td>The MIT Press</td>
<td><nobr>2022</nobr></td>
<td>English</td>
<td>854 / 854</td>
<td><nobr><a href="/file.php?id=97890631">50 MB</a></nobr></td>
<td>pdf</td>
<td><nobr><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=615b614a406e379ac2a01fd278414216" title="libgen"><span class="badge badge-primary">1</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/615b614a406e379ac2a01fd278414216" title="Randombook"><span class="badge badge-primary">2</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/615b614a406e379ac2a01fd278414216?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">3</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/615b614a406e379ac2a01fd278414216" title="libgen.pw"><span class="badge badge-primary">4</span></a> </nobr></td>
</tr><tr>
<td><a href="edition.php?id=141871023"><img src="/covers/4016000/c1c11dd67a068d0cd899d9bc57f9fd7f_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><b>Adaptive Computation and Machine Learning<a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=141871023" title="Add/Edit : 2023-02-08/2023-03-09; ID: 99041108&lt;br&gt;Kevin P. Murphy - Probabilistic Machine Learning 1(2022, MIT Press)"><i></i></a></b><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=141871023" title="Add/Edit : 2023-02-08/2023-03-09; ID: 99041108&lt;br&gt;Kevin P. Murphy - Probabilistic Machine Learning 1(2022, MIT Press)">Probabilistic Machine Learning: An Introduction (Adaptive Computation and Machine Learning series) <i>1</i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=141871023" title="Add/Edit : 2023-02-08/2023-03-09; ID: 99041108&lt;br&gt;Kevin P. Murphy - Probabilistic Machine Learning 1(2022, MIT Press)"><i><font color="green"> 0262046822; 9780262046824</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 4016265</span></nobr>
</td>
<td>Kevin P. Murphy</td>
<td>The MIT Press</td>
<td><nobr>2022</nobr></td>
<td>English</td>
<td>0 / 854</td>
<td><nobr><a href="/file.php?id=99041108">87 MB</a></nobr></td>
<td>pdf</td>
<td><nobr><a data-html="true" data-placement="bottom" data-toggle="tooltip" href="/ads.php?md5=c1c11dd67a068d0cd899d9bc57f9fd7f" title="libgen"><span class="badge badge-primary">1</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://randombook.org/book/c1c11dd67a068d0cd899d9bc57f9fd7f" title="Randombook"><span class="badge badge-primary">2</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://en.annas-archive.gl/md5/c1c11dd67a068d0cd899d9bc57f9fd7f?r=Ax2w6jC" title="anna's archive"><span class="badge badge-primary">3</span></a> <a data-html="true" data-placement="bottom" data-toggle="tooltip" href="https://libgen.pw/book/c1c11dd67a068d0cd899d9bc57f9fd7f" title="libgen.pw"><span class="badge badge-primary">4</span></a> </nobr></td>
</tr><tr>
<td><a href="edition.php?id=138226359"><img src="/covers/2449000/6ab53d6bd918569dbbf95eed84ac51ab_small.jpg" style="max-height:70px;max-width:150px;height:auto;width:auto;"/></a></td>
<td><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=138226359" title="Add/Edit : 2019-12-14/2019-12-21; ID: 93435968&lt;br&gt;Packt.Python.Machine.Learning.3rd.Edition.1789955750">Python Machine Learning: Machine Learning and Deep Learning with Python, scikit-learn, and TensorFlow 2 <i>3</i></a><br/><a data-html="true" data-placement="right" data-toggle="tooltip" href="edition.php?id=138226359" title="Add/Edit : 2019-12-14/2019-12-21; ID: 93435968&lt;br&gt;Packt.Python.Machine.Learning.3rd.Edition.1789955750"><i><font color="green"> 1789955750; 9781789955750</font></i></a>
<nobr><span class="badge badge-primary"><a data-html="true" data-placement="bottom" data-toggle="tooltip" title="Book">b</a></span>
<span class="badge badge-secondary">l 2449092</span></nobr>
</td>
<td>Sebastian Raschka, Vahid Mirjalili</td>
<td>Packt Publishing - ebooks Account</td>
<td><nobr>2019</nobr></td>
<td>English</td>
<td>771 / 770</td>
<td><nobr><a href="/file.php?id=93435968">26 MB</a></nobr></td>
<td>pdf</td>

In [4]:
headers = table.find("thead")
headers = [col.text.strip().replace("↕","").strip().replace("\r","").replace("\n","") for col in headers.find_all("th")][1:]
headers[0] = "Name"
headers

['Name',
 'Author(s)',
 'Publisher',
 'Year',
 'Language',
 'Pages',
 'Size',
 'Ext.',
 'Mirrors']

In [6]:
df = pd.DataFrame(columns = headers)
df

Empty DataFrame
Columns: [Name, Author(s), Publisher, Year, Language, Pages, Size, Ext., Mirrors]
Index: []

In [7]:
image_src = []
title_data = []
body = soup.find("tbody")
md5 = []
for row in body.find_all("tr"):
    row_data = [td for td in row.find_all("td")]
    image_src.append(row_data[0].find("img")["src"])
    if row_data[1].find("a").text == "":
       title_data.append(row_data[1].find("b").text)
    else:
        title_data.append(row_data[1].find("a").text)
    other_columns = [td.text for td in row.find_all("td")[1:]]
    md5.append(row_data[9].find("a")["href"].split("=")[-1].split("/")[-1])

    lenght = len(df)

    df.loc[lenght] = other_columns
df

,Name,Author(s),Publisher,Year,Language,Pages,Size,Ext.,Mirrors
0,Chapman & Hall/CRC machine learning & pattern ...,"Botev, Zdravko I.; Kroese, Dirk P.; Taimre, Th...",Chapman & Hall/CRC,2020,English,"536 / xxi, 513 pages : illustrations, charts; ...",15 MB,pdf,1 2 3 4
1,Interpretable Machine Learning with Python - S...,"Masís, Serg",Packt Publishing,2022,English,0 / 357,11 MB,epub,1 2 3 4
2,The Machine Learning Solutions Architect Handb...,"Ping, David",Packt Publishing,2022,English,40 / 90,4 MB,epub,1 2 3 4
3,Machine Learning Algorithms for Classification...,"Schapire, Rob (author)",,,,58,321 kB,pdf,Libgen Sci-Hub Randombook libgen.pw Anna's arch
4,Swarm Intelligence and Machine Learning 97810...,Shikha Agarwal & Manish Gupta & Jitendra Agraw...,,2022,English,0,10 MB,fb2,1 2 3 4
...,...,...,...,...,...,...,...,...,...
95,Machine learning with AWS explore the power of...,"Jackovich, Jeffrey;Richards, Ruze","Packt Publishing, Limited",2018,English,0 / 1 v,18 MB,epub,1 2 3 4
96,Monetizing machine learning: quickly turn Pyth...,"Amunategui, Manuel;Roopaei, Mehdi",Apress,2018,English,"510 / xli, 482 pages : illustrations ; 26 cm",22 MB,pdf,1 2 3 4
97,Mastering Machine Learning Algorithms Expert t...,"Bonaccorso, Giuseppe",Packt Publishing,2020;2018,English,0,79 MB,epub,1 2 3 4
98,Mastering Machine Learning Algorithms Expert t...,"Bonaccorso, Giuseppe",Packt Publishing,2020;2019,English,0,198 MB,mobi,1 2 3 4
99,Mastering Machine Learning Algorithms Expert t...,"Bonaccorso, Giuseppe",Packt Publishing,2020;2019,English,0,94 MB,epub,1 2 3 4

In [24]:
for i,item in enumerate(title_data):
    df["Name"][i] = item

df["Name"]

0     Chapman & Hall/CRC machine learning & pattern ...
1     Interpretable Machine Learning with Python - S...
2     The Machine Learning Solutions Architect Handb...
3     Machine Learning Algorithms for Classification...
4              Swarm Intelligence and Machine Learning
                            ...
95    Machine learning with AWS explore the power of...
96    Monetizing machine learning: quickly turn Pyth...
97    Mastering Machine Learning Algorithms Expert t...
98    Mastering Machine Learning Algorithms Expert t...
99    Mastering Machine Learning Algorithms Expert t...
Name: Name, Length: 100, dtype: object

In [25]:
for i,item in enumerate(md5):
    df["Mirrors"][i] = "https://annas-archive.gl/md5/" + item
df["Author(s)"]= df["Author(s)"].str.replace(";",",")
df.loc[0]

Name         Chapman & Hall/CRC machine learning & pattern ...
Author(s)    Botev, Zdravko I., Kroese, Dirk P., Taimre, Th...
Publisher                                   Chapman & Hall/CRC
Year                                                      2020
Language                                               English
Pages        536 / xxi, 513 pages : illustrations, charts; ...
Size                                                     15 MB
Ext.                                                       pdf
Mirrors      https://annas-archive.gl/md5/9ef62d66f3895c959...
Name: 0, dtype: object

In [29]:
df.drop_duplicates(inplace = True,)
df["Name"].value_counts()

Name
Learning path                                                                                                                                                                                                                                                                                                                                                                                                                                          9
2                                                                                                                                                                                                                                                                                                                                                                                                                                                      6
Community experience distilled                                                                                                                                                                                                                                                                                                                                                                                                                         6
Swarm Intelligence and Machine Learning                                                                                                                                                                                                                                                                                                                                                                                                                5
Adaptive Computation and Machine Learning                                                                                                                                                                                                                                                                                                                                                                                                              5
Hands-On Network Machine Learning with Python 1                                                                                                                                                                                                                                                                                                                                                                                                        4
Mastering Machine Learning Algorithms Expert techniques for implementing popular machine learning algorithms, fine-tuning your models, and understanding how they work 2nd Edition                                                                                                                                                                                                                                                                     3
Graph Machine Learning: Learn about the latest advancements in graph data to build robust machine learning models 2                                                                                                                                                                                                                                                                                                                                    2
Chapman & Hall/CRC machine learning & pattern recognition series                                                                                                                                                                                                                                                                                                                                                                                       2
Chapman & Hall/CRC Machine Learning & Pattern Recognition                                                                                                                                                                                                                                                                                                                                                                                              2
Hands-On Unsupervised Learning Using Python: How to Build Applied Machine Learning Solutions from Unlabeled Data Paperback                                                                                                                                                                                                                                                                                                                             2
Hands-on data science and Python machine learning : perform data mining and machine learning efficiently using Python and Spark                                                                                                                                                                                                                                                                                                                        2
Hands-On Machine Learning with Scikit-Learn and PyTorch Concepts, Tools, and Techniques to Build Intelligent Systems 1                                                                                                                                                                                                                                                                                                                                 2
Cognitive Technologies                                                                                                                                                                                                                                                                                                                                                                                                                                 2
Machine Learning with PySpark: With Natural Language Processing and Recommender Systems 1st ed.                                                                                                                                                                                                                                                                                                                                                        2
Encyclopedia of Machine Learning and Data Mining 2nd ed. 2017                                                                                                                                                                                                                                                                                                                                                                                          2
Machine Learning for Beginners: The Ultimate Guide to Learn and Understand Machine Learning – A Practical Approach to Master Machine Learning to Improve and Increase Business Results                                                                                                                                                                                                                                                                 2
Lecture Notes in Computer Science                                                                                                                                                                                                                                                                                                                                                                                                                      2
Chapman & Hall/CRC machine learning & pattern recognition                                                                                                                                                                                                                                                                                                                                                                                              1
Fundamentals of Machine Learning for Predictive Data Analytics                                                                                                                                                                                                                                                                                                                                                                                         1
Machine Learning for Time-Series with Python: Forecast, predict, and detect anomalies with state-of-the-art machine learning methods 1                                                                                                                                                                                                                                                                                                                 1
Python Machine Learning: Machine Learning and Deep Learning with Python, scikit-learn, and TensorFlow 2 3                                                                                                                                                                                                                                                                                                                                              1
The Machine Learning Solutions Architect Handbook (Early Access)                                                                                                                                                                                                                                                                                                                                                                                       1
Python Machine Learning 1                                                                                                                                                                                                                                                                                                                                                                                                                              1
Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification Machine Learning Algorithms for Classification                                                                                                                                                                                                             1
Interpretable Machine Learning with Python - Second Edition (Early Access) 2nd                                                                                                                                                                                                                                                                                                                                                                         1
Part I Overview of Adversarial Machine Learning 1 Introduction 3 1.1 Motivation 4 1.2 A Principled Approach to Secure Learning 11 1.3 Chronology of Secure Learning 14 1.4 Overview 17 2 Background and Notation 20 2.1 Basic Notation 20 2.2 Statistical Machine Learning 20 2.2.1 Data 22 2.2.2 Hypothesis Space 24 2.2.3 The Learning Model 24 2.2.4 Supervised Learning 25 2.2.5 Other Learning Paradigms 28 3 A Framework for Secure Learning     1
PYTHON MACHINE LEARNING: machine learning algorithms for beginners - data management and analitics for approaching deep learning and neural networks from scratch                                                                                                                                                                                                                                                                                      1
Applied Natural Language Processing with Python: Implementing Machine Learning and Deep Learning Algorithms for Natural Language Processing 1                                                                                                                                                                                                                                                                                                          1
Mastering Machine Learning with Spark 2.x: Harness the potential of machine learning, through spark 1                                                                                                                                                                                                                                                                                                                                                  1
Adaptive Computation and Machine Learning series                                                                                                                                                                                                                                                                                                                                                                                                       1
Applied Machine Learning and AI for Engineers: Solve Business Problems That Can't Be Solved Algorithmically 1                                                                                                                                                                                                                                                                                                                                          1
Machine Learning & Pattern Recognition                                                                                                                                                                                                                                                                                                                                                                                                                 1
Machine Learning: An Essential Guide to Machine Learning for Beginners                                                                                                                                                                                                                                                                                                                                                                                 1
Adaptive computation and machine learning                                                                                                                                                                                                                                                                                                                                                                                                              1
The Machine Learning Solutions Architect Handbook 2nd Edition                                                                                                                                                                                                                                                                                                                                                                                          1
Machine Learning for iOS Developers 1                                                                                                                                                                                                                                                                                                                                                                                                                  1
Keras to Kubernetes: The Journey of a Machine Learning Model to Production 1                                                                                                                                                                                                                                                                                                                                                                           1
Machine Learning for OpenCV: Intelligent image processing with Python 1                                                                                                                                                                                                                                                                                                                                                                                1
Hands-On Unsupervised Learning Using Python: How to Build Applied Machine Learning Solutions from Unlabeled Data 1                                                                                                                                                                                                                                                                                                                                     1
Morgan Kaufmann Series in Data Management Systems                                                                                                                                                                                                                                                                                                                                                                                                      1
Machine Learning Algorithms Paperback                                                                                                                                                                                                                                                                                                                                                                                                                  1
Machine Learning From Weak Supervision An Empirical Risk Minimization Approach                                                                                                                                                                                                                                                                                                                                                                         1
Grokking Machine Learning 1                                                                                                                                                                                                                                                                                                                                                                                                                            1
Practical Simulations for Machine Learning: Using Synthetic Data for AI 1                                                                                                                                                                                                                                                                                                                                                                              1

In [26]:
df.to_excel("Machine_learning_textbooks.xlsx",index=False)